-- 2022년 1월 판매 데이터 기준
-- 저자 별, 카테고리 별 매출액 구하기
SELECT TB1.AUTHOR_ID, TB2.AUTHOR_NAME, TB1.CATEGORY, SUM(TB1.SALES) AS SALES 
FROM (
    SELECT A.BOOK_ID, B.AUTHOR_ID, B.CATEGORY, SUM(SALES) * B.PRICE AS SALES
    FROM BOOK_SALES A
    JOIN BOOK B
    ON A.BOOK_ID = B.BOOK_ID
    WHERE DATE_FORMAT(A.SALES_DATE, '%Y-%m') = '2022-01'
    GROUP BY A.BOOK_ID
) TB1
JOIN AUTHOR TB2
ON TB1.AUTHOR_ID = TB2.AUTHOR_ID 
GROUP BY TB1.AUTHOR_ID, TB1.CATEGORY
ORDER BY TB1.AUTHOR_ID, TB1.CATEGORY DESC;
