SELECT TB1.REST_ID, TB1.REST_NAME, TB1.FOOD_TYPE, TB1.FAVORITES, TB1.ADDRESS, ROUND(AVG(TB2.REVIEW_SCORE), 2) AS SCORE 
FROM REST_INFO TB1
JOIN REST_REVIEW TB2
ON TB1.REST_ID = TB2.REST_ID 
WHERE TB1.ADDRESS LIKE '서울%' 
GROUP BY TB1.REST_ID
ORDER BY AVG(TB2.REVIEW_SCORE) DESC, TB1.FAVORITES DESC;
