-- 고양이와 개가 각각 몇 마리인지 조회
-- 고양이, 개 순으로
SELECT ANIMAL_TYPE, COUNT(*) AS COUNT 
FROM ANIMAL_INS 
WHERE ANIMAL_TYPE IN ('Cat', 'Dog')
GROUP BY ANIMAL_TYPE
ORDER BY CASE ANIMAL_TYPE WHEN 'Cat' THEN 0 ELSE 1 END;
