-- 각 세대별 자식이 없는 개체의 수 와 세대 출력
-- 세대 오름차순
WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GEN  
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL 
    UNION ALL
    SELECT A.ID, CTE.ID, (GEN + 1) AS GEN
    FROM ECOLI_DATA A 
    JOIN CTE ON CTE.ID = A.PARENT_ID 
) 
SELECT COUNT(*) AS COUNT, A.GEN AS GENERATION 
FROM CTE A
WHERE NOT EXISTS (
    SELECT 1 
    FROM CTE B
    WHERE A.ID = B.PARENT_ID
)
GROUP BY A.GEN;