WITH RECURSIVE HOUR_TABLE AS (
    SELECT 0 AS HOUR
    UNION
    SELECT HOUR + 1
    FROM HOUR_TABLE
    WHERE HOUR < 23
)
SELECT A.HOUR, COUNT(B.ANIMAL_ID) AS COUNT
FROM HOUR_TABLE A 
LEFT JOIN ANIMAL_OUTS B
ON A.HOUR = HOUR(B.DATETIME)
GROUP BY A.HOUR
ORDER BY A.HOUR