SELECT T1.ITEM_ID, T2.ITEM_NAME, T2.RARITY  
FROM ITEM_TREE T1
JOIN ITEM_INFO T2
ON T1.ITEM_ID = T2.ITEM_ID 
WHERE T1.PARENT_ITEM_ID IN (
    SELECT ITEM_ID 
    FROM ITEM_INFO 
    WHERE RARITY = 'RARE'
)
ORDER BY T1.ITEM_ID DESC;