-- ID, GENOTYPE, PARENT_GENOTYPE 출력
-- 부모의 형질을 가지고 있는지
SELECT 
    B.ID, B.GENOTYPE, A.GENOTYPE AS PARENT_GENOTYPE 
FROM ECOLI_DATA A
JOIN ECOLI_DATA B
ON A.ID = B.PARENT_ID 
WHERE (A.GENOTYPE & B.GENOTYPE) = A.GENOTYPE 
ORDER BY B.ID ASC;