-- 물고기 종류 별 가장 큰 물고기
-- ID, 이름, 길이 출력
SELECT A.ID, C.FISH_NAME, B.LENGTH 
FROM FISH_INFO A 
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH 
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) B
ON A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.LENGTH 
JOIN FISH_NAME_INFO C 
ON A.FISH_TYPE = C.FISH_TYPE
ORDER BY A.ID;