-- 코드를 입력하세요
SELECT
    TB1.TITLE, 
    TB1.BOARD_ID, 
    TB2.REPLY_ID, 
    TB2.WRITER_ID, 
    TB2.CONTENTS, 
    DATE_FORMAT(TB2.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS TB1
JOIN USED_GOODS_REPLY AS TB2
ON TB1.BOARD_ID = TB2.BOARD_ID
WHERE TB1.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31' 
ORDER BY TB2.CREATED_DATE ASC, TB1.TITLE ASC;